// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BookingResponse struct {
	Status      PaymentStatus `json:"status"`
	Message     string        `json:"message"`
	SeatID      string        `json:"seatId"`
	ExpiresAtMs *int          `json:"expiresAtMs,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Seat struct {
	ID          string     `json:"id"`
	Status      SeatStatus `json:"status"`
	UserID      *string    `json:"userId,omitempty"`
	LockedAtMs  *int       `json:"lockedAtMs,omitempty"`
	ExpiresAtMs *int       `json:"expiresAtMs,omitempty"`
}

type SeatEvent struct {
	SeatID      string     `json:"seatId"`
	Status      SeatStatus `json:"status"`
	UserID      *string    `json:"userId,omitempty"`
	TimestampMs int        `json:"timestampMs"`
}

type Subscription struct {
}

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "PENDING"
	PaymentStatusSuccess PaymentStatus = "SUCCESS"
	PaymentStatusFailed  PaymentStatus = "FAILED"
	PaymentStatusExpired PaymentStatus = "EXPIRED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusSuccess,
	PaymentStatusFailed,
	PaymentStatusExpired,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusSuccess, PaymentStatusFailed, PaymentStatusExpired:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SeatStatus string

const (
	SeatStatusAvailable SeatStatus = "AVAILABLE"
	SeatStatusLocked    SeatStatus = "LOCKED"
	SeatStatusBooked    SeatStatus = "BOOKED"
)

var AllSeatStatus = []SeatStatus{
	SeatStatusAvailable,
	SeatStatusLocked,
	SeatStatusBooked,
}

func (e SeatStatus) IsValid() bool {
	switch e {
	case SeatStatusAvailable, SeatStatusLocked, SeatStatusBooked:
		return true
	}
	return false
}

func (e SeatStatus) String() string {
	return string(e)
}

func (e *SeatStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SeatStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SeatStatus", str)
	}
	return nil
}

func (e SeatStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SeatStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SeatStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
