// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/seat/v1/seat.proto

package seatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatService_LockSeat_FullMethodName      = "/seat.v1.SeatService/LockSeat"
	SeatService_ReleaseSeat_FullMethodName   = "/seat.v1.SeatService/ReleaseSeat"
	SeatService_BookSeat_FullMethodName      = "/seat.v1.SeatService/BookSeat"
	SeatService_GetSeatStatus_FullMethodName = "/seat.v1.SeatService/GetSeatStatus"
	SeatService_SeatStream_FullMethodName    = "/seat.v1.SeatService/SeatStream"
)

// SeatServiceClient is the client API for SeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatServiceClient interface {
	// Lock a seat (5 minute timer starts automatically)
	LockSeat(ctx context.Context, in *LockSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error)
	// Release seat (called on timeout or manual cancel)
	ReleaseSeat(ctx context.Context, in *ReleaseSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error)
	// Confirm booking after payment successful
	BookSeat(ctx context.Context, in *BookSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error)
	// Get current seat status
	GetSeatStatus(ctx context.Context, in *SeatStatusRequest, opts ...grpc.CallOption) (*SeatResponse, error)
	// Bi-directional streaming for real-time seat updates
	SeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SeatEvent, SeatEvent], error)
}

type seatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatServiceClient(cc grpc.ClientConnInterface) SeatServiceClient {
	return &seatServiceClient{cc}
}

func (c *seatServiceClient) LockSeat(ctx context.Context, in *LockSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatResponse)
	err := c.cc.Invoke(ctx, SeatService_LockSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) ReleaseSeat(ctx context.Context, in *ReleaseSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatResponse)
	err := c.cc.Invoke(ctx, SeatService_ReleaseSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) BookSeat(ctx context.Context, in *BookSeatRequest, opts ...grpc.CallOption) (*SeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatResponse)
	err := c.cc.Invoke(ctx, SeatService_BookSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) GetSeatStatus(ctx context.Context, in *SeatStatusRequest, opts ...grpc.CallOption) (*SeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatResponse)
	err := c.cc.Invoke(ctx, SeatService_GetSeatStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) SeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SeatEvent, SeatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SeatService_ServiceDesc.Streams[0], SeatService_SeatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SeatEvent, SeatEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SeatService_SeatStreamClient = grpc.BidiStreamingClient[SeatEvent, SeatEvent]

// SeatServiceServer is the server API for SeatService service.
// All implementations must embed UnimplementedSeatServiceServer
// for forward compatibility.
type SeatServiceServer interface {
	// Lock a seat (5 minute timer starts automatically)
	LockSeat(context.Context, *LockSeatRequest) (*SeatResponse, error)
	// Release seat (called on timeout or manual cancel)
	ReleaseSeat(context.Context, *ReleaseSeatRequest) (*SeatResponse, error)
	// Confirm booking after payment successful
	BookSeat(context.Context, *BookSeatRequest) (*SeatResponse, error)
	// Get current seat status
	GetSeatStatus(context.Context, *SeatStatusRequest) (*SeatResponse, error)
	// Bi-directional streaming for real-time seat updates
	SeatStream(grpc.BidiStreamingServer[SeatEvent, SeatEvent]) error
	mustEmbedUnimplementedSeatServiceServer()
}

// UnimplementedSeatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatServiceServer struct{}

func (UnimplementedSeatServiceServer) LockSeat(context.Context, *LockSeatRequest) (*SeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockSeat not implemented")
}
func (UnimplementedSeatServiceServer) ReleaseSeat(context.Context, *ReleaseSeatRequest) (*SeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeat not implemented")
}
func (UnimplementedSeatServiceServer) BookSeat(context.Context, *BookSeatRequest) (*SeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BookSeat not implemented")
}
func (UnimplementedSeatServiceServer) GetSeatStatus(context.Context, *SeatStatusRequest) (*SeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatStatus not implemented")
}
func (UnimplementedSeatServiceServer) SeatStream(grpc.BidiStreamingServer[SeatEvent, SeatEvent]) error {
	return status.Error(codes.Unimplemented, "method SeatStream not implemented")
}
func (UnimplementedSeatServiceServer) mustEmbedUnimplementedSeatServiceServer() {}
func (UnimplementedSeatServiceServer) testEmbeddedByValue()                     {}

// UnsafeSeatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatServiceServer will
// result in compilation errors.
type UnsafeSeatServiceServer interface {
	mustEmbedUnimplementedSeatServiceServer()
}

func RegisterSeatServiceServer(s grpc.ServiceRegistrar, srv SeatServiceServer) {
	// If the following call panics, it indicates UnimplementedSeatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatService_ServiceDesc, srv)
}

func _SeatService_LockSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).LockSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_LockSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).LockSeat(ctx, req.(*LockSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_ReleaseSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).ReleaseSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_ReleaseSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).ReleaseSeat(ctx, req.(*ReleaseSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_BookSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).BookSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_BookSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).BookSeat(ctx, req.(*BookSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_GetSeatStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).GetSeatStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_GetSeatStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).GetSeatStatus(ctx, req.(*SeatStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_SeatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SeatServiceServer).SeatStream(&grpc.GenericServerStream[SeatEvent, SeatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SeatService_SeatStreamServer = grpc.BidiStreamingServer[SeatEvent, SeatEvent]

// SeatService_ServiceDesc is the grpc.ServiceDesc for SeatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat.v1.SeatService",
	HandlerType: (*SeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockSeat",
			Handler:    _SeatService_LockSeat_Handler,
		},
		{
			MethodName: "ReleaseSeat",
			Handler:    _SeatService_ReleaseSeat_Handler,
		},
		{
			MethodName: "BookSeat",
			Handler:    _SeatService_BookSeat_Handler,
		},
		{
			MethodName: "GetSeatStatus",
			Handler:    _SeatService_GetSeatStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeatStream",
			Handler:       _SeatService_SeatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/seat/v1/seat.proto",
}

const (
	PaymentService_StartPaymentTimer_FullMethodName = "/seat.v1.PaymentService/StartPaymentTimer"
	PaymentService_ConfirmPayment_FullMethodName    = "/seat.v1.PaymentService/ConfirmPayment"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	// Start payment timer (5 minutes)
	StartPaymentTimer(ctx context.Context, in *PaymentTimerRequest, opts ...grpc.CallOption) (*PaymentTimerResponse, error)
	// Confirm payment and book seat
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*PaymentTimerResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) StartPaymentTimer(ctx context.Context, in *PaymentTimerRequest, opts ...grpc.CallOption) (*PaymentTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentTimerResponse)
	err := c.cc.Invoke(ctx, PaymentService_StartPaymentTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*PaymentTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentTimerResponse)
	err := c.cc.Invoke(ctx, PaymentService_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	// Start payment timer (5 minutes)
	StartPaymentTimer(context.Context, *PaymentTimerRequest) (*PaymentTimerResponse, error)
	// Confirm payment and book seat
	ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*PaymentTimerResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) StartPaymentTimer(context.Context, *PaymentTimerRequest) (*PaymentTimerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPaymentTimer not implemented")
}
func (UnimplementedPaymentServiceServer) ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*PaymentTimerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_StartPaymentTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StartPaymentTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_StartPaymentTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StartPaymentTimer(ctx, req.(*PaymentTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ConfirmPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPaymentTimer",
			Handler:    _PaymentService_StartPaymentTimer_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _PaymentService_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seat/v1/seat.proto",
}
