package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"log"

	"github.com/soumyaojha/ticket-booking-system/api-gateway/graph/model"
)

// LockSeat is the resolver for the lockSeat field.
func (r *mutationResolver) LockSeat(ctx context.Context, seatID string, userID string) (*model.BookingResponse, error) {
	log.Printf("Locking seat %s for user %s\n", seatID, userID)

	// Start payment timer (Payment Service locks the seat and starts the countdown).
	paymentResp, err := r.Payment.StartPaymentTimer(ctx, seatID, userID, 1000)
	if err != nil {
		log.Printf("Error starting payment timer: %v\n", err)
		return &model.BookingResponse{
			Status:  model.PaymentStatusFailed,
			Message: "Failed to start payment timer: " + err.Error(),
			SeatID:  seatID,
		}, nil
	}

	log.Printf("Payment response: %+v\n", paymentResp)

	seatResp, err := r.Inventory.GetSeatStatus(ctx, seatID)
	if err != nil {
		log.Printf("Error getting seat status after lock: %v\n", err)
		return &model.BookingResponse{
			Status:  model.PaymentStatusPending,
			Message: "Seat locked, payment timer started (expiry unknown)",
			SeatID:  seatID,
		}, nil
	}

	expiresAtMs := int(seatResp.ExpiresAtMs)
	return &model.BookingResponse{
		Status:      model.PaymentStatusPending,
		Message:     "Seat locked, payment timer started for 5 minutes",
		SeatID:      seatID,
		ExpiresAtMs: &expiresAtMs,
	}, nil
}

// ConfirmPayment is the resolver for the confirmPayment field.
func (r *mutationResolver) ConfirmPayment(ctx context.Context, seatID string, userID string, transactionID string) (*model.BookingResponse, error) {
	log.Printf("Confirming payment for seat %s (user: %s, transaction: %s)\n", seatID, userID, transactionID)

	// Confirm payment
	paymentResp, err := r.Payment.ConfirmPayment(ctx, seatID, userID, 1000, transactionID)
	if err != nil {
		log.Printf("Error confirming payment: %v\n", err)
		return &model.BookingResponse{
			Status:  model.PaymentStatusFailed,
			Message: "Failed to confirm payment: " + err.Error(),
			SeatID:  seatID,
		}, nil
	}

	// Verify payment was successful
	if paymentResp.Status != "SUCCESS" {
		return &model.BookingResponse{
			Status:  model.PaymentStatusFailed,
			Message: "Payment not successful: " + paymentResp.Message,
			SeatID:  seatID,
		}, nil
	}

	return &model.BookingResponse{
		Status:  model.PaymentStatusSuccess,
		Message: "Seat successfully booked after payment confirmation",
		SeatID:  seatID,
	}, nil
}

// ReleaseSeat is the resolver for the releaseSeat field.
func (r *mutationResolver) ReleaseSeat(ctx context.Context, seatID string) (string, error) {
	log.Printf("Releasing seat %s\n", seatID)

	_, err := r.Inventory.ReleaseSeat(ctx, seatID, "MANUAL_CANCEL")
	if err != nil {
		log.Printf("Error releasing seat: %v\n", err)
		return "Failed to release seat: " + err.Error(), nil
	}

	return "Seat released successfully", nil
}

// SeatStatus is the resolver for the seatStatus field.
func (r *queryResolver) SeatStatus(ctx context.Context, seatID string) (*model.Seat, error) {
	resp, err := r.Inventory.GetSeatStatus(ctx, seatID)
	if err != nil {
		log.Printf("Error getting seat status: %v\n", err)
		return nil, err
	}

	status := model.SeatStatusAvailable
	if resp.Status == "LOCKED" {
		status = model.SeatStatusLocked
	} else if resp.Status == "BOOKED" {
		status = model.SeatStatusBooked
	}

	return &model.Seat{
		ID:          resp.SeatId,
		Status:      status,
		UserID:      &resp.UserId,
		LockedAtMs:  ptr(int(resp.LockedAtMs)),
		ExpiresAtMs: ptr(int(resp.ExpiresAtMs)),
	}, nil
}

// AvailableSeats is the resolver for the availableSeats field.
func (r *queryResolver) AvailableSeats(ctx context.Context) ([]*model.Seat, error) {
	// This would query all seats from inventory service
	// For now, return empty list as we need more infrastructure
	return []*model.Seat{}, nil
}

// SeatUpdated is the resolver for the seatUpdated field.
func (r *subscriptionResolver) SeatUpdated(ctx context.Context) (<-chan *model.SeatEvent, error) {
	ch, _ := r.subscribeAll(ctx)
	return ch, nil
}

// SeatEvents is the resolver for the seatEvents field.
func (r *subscriptionResolver) SeatEvents(ctx context.Context, seatID string) (<-chan *model.SeatEvent, error) {
	ch, _ := r.subscribeSeat(ctx, seatID)
	return ch, nil
}

func ptr(v int) *int {
	return &v
}

// Mutation returns MutationResolver implementation.

func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) BookSeat(ctx context.Context, seatID string) (*model.BookingResponse, error) {
	panic(fmt.Errorf("not implemented: BookSeat - bookSeat"))
}
*/
